/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra1;

import javax.swing.JOptionPane;

/**
 *
 * @author javier
 */
public class Asignarse_curso extends javax.swing.JFrame {

    /**
     * Creates new form Asignarse_curso
     */
    public Asignarse_curso() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Asignarse a Curso");
        
        jLabel1.setText("Estudiante: " + Proyectoprogra1.alumnoLogeado.toString());

        for (Curso c : Proyectoprogra1.cursos) {
            Box_cursos.addItem(c.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_salir1 = new javax.swing.JButton();
        btn_asignar = new javax.swing.JButton();
        Box_cursos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Asignarse a Curso");

        jLabel1.setText("Estudiante:");

        jLabel2.setText("Curso:");

        btn_salir1.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir1.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir1.setText("Salir");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        btn_asignar.setBackground(new java.awt.Color(0, 204, 0));
        btn_asignar.setForeground(new java.awt.Color(255, 255, 255));
        btn_asignar.setText("Asignar");
        btn_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_salir1)
                        .addGap(63, 63, 63)
                        .addComponent(btn_asignar)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Box_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Box_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_asignar)
                    .addComponent(btn_salir1))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        BienvenidaAlumno a = new BienvenidaAlumno();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarActionPerformed
        String datoscurso = Box_cursos.getSelectedItem().toString();
        Alumno datosalumno = Proyectoprogra1.alumnoLogeado;

        Alumno alumnoSeleccionado = null;
        Curso cursoSeleccionado = null;

        for (Alumno a : Proyectoprogra1.alumnos) {
            if (a.equals(datosalumno)) {
                alumnoSeleccionado = a;
                break;
            }
        }
        for (Curso e : Proyectoprogra1.cursos) {
            if (e.toString().equals(datoscurso)) {
                cursoSeleccionado = e;
                break;
            }
        }

        if (alumnoSeleccionado != null && cursoSeleccionado != null) {
            boolean alumnoEncontrado = false;
            
            int contadorCursos = 0;
            for (Alumno a : cursoSeleccionado.getAlumnos()) {
                if (a.getCarnet().equals(alumnoSeleccionado.getCarnet())) {
                    alumnoEncontrado = true;
                    break;
                }
            }
            for (Curso curso : Proyectoprogra1.cursos) {
                for (Alumno a : curso.getAlumnos()) {
                    if (a.getCarnet().equals(alumnoSeleccionado.getCarnet())) {
                        contadorCursos++;
                    }
                }
            }
            
            if (alumnoEncontrado) {
                JOptionPane.showMessageDialog(this, "Ya estas asignado a este curso.");
                return;
            }
            if (contadorCursos >= 5) {
                JOptionPane.showMessageDialog(this, "Ya tienes asignado 5 cursos.");
                return;
            }
            if (cursoSeleccionado.getAlumnos().size() >= 10) {
                JOptionPane.showMessageDialog(this, "El curso ya tiene 10 alumnos.");
                return;
            }
            Alumno a = new Alumno();
            a.setNombre(alumnoSeleccionado.getNombre());
            a.setApellido(alumnoSeleccionado.getApellido());
            a.setCarnet(alumnoSeleccionado.getCarnet());
            a.setPassword(alumnoSeleccionado.getPassword());
            a.setNota(alumnoSeleccionado.getNota());
            cursoSeleccionado.getAlumnos().add(a);

            JOptionPane.showMessageDialog(this, "Asignado exitosamente.");
        }
    }//GEN-LAST:event_btn_asignarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_cursos;
    private javax.swing.JButton btn_asignar;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
