/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra1;

/**
 *
 * @author javier
 */
public class BienvenidaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form BienvenidaProfesor
     */
    public BienvenidaProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Panel Profesor");
        
        jLabel1.setText("Bienvenido profesor: "+Proyectoprogra1.profesorLogeado.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_miscursos = new javax.swing.JMenuItem();
        btn_alumnosasignados = new javax.swing.JMenuItem();
        btn_miperfil = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("AnjaliOldLipi", 3, 18)); // NOI18N
        jLabel1.setText("Bienvenido profesor");

        jMenu1.setText("Cursos");

        btn_miscursos.setText("Mis cursos");
        btn_miscursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_miscursosActionPerformed(evt);
            }
        });
        jMenu1.add(btn_miscursos);

        btn_alumnosasignados.setText("Alumnos asignados");
        btn_alumnosasignados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnosasignadosActionPerformed(evt);
            }
        });
        jMenu1.add(btn_alumnosasignados);

        jMenuBar1.add(jMenu1);

        btn_miperfil.setText("Mi Perfil");
        btn_miperfil.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                btn_miperfilMenuSelected(evt);
            }
        });
        btn_miperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_miperfilActionPerformed(evt);
            }
        });
        jMenuBar1.add(btn_miperfil);

        logout.setBackground(new java.awt.Color(255, 153, 153));
        logout.setForeground(new java.awt.Color(204, 0, 0));
        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        logout.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                logoutMenuSelected(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_miperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_miperfilActionPerformed
        Miperfil_profesor p = new Miperfil_profesor();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_miperfilActionPerformed

    private void btn_miperfilMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_btn_miperfilMenuSelected
        Miperfil_profesor p = new Miperfil_profesor();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_miperfilMenuSelected

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void btn_miscursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_miscursosActionPerformed
        vermiscursos_profesor p = new vermiscursos_profesor();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_miscursosActionPerformed

    private void btn_alumnosasignadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnosasignadosActionPerformed
        alumnos_asignados_profesor p = new alumnos_asignados_profesor();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_alumnosasignadosActionPerformed

    private void logoutMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_logoutMenuSelected
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMenuSelected

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_alumnosasignados;
    private javax.swing.JMenu btn_miperfil;
    private javax.swing.JMenuItem btn_miscursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logout;
    // End of variables declaration//GEN-END:variables
}
