/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra1;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

/**
 *
 * @author javier
 */
public class Consultar_Alumno extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Alumno
     */
    public Consultar_Alumno() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consultar Alumnos Creados");

        DefaultTableModel data = new DefaultTableModel(new String[]{"Carnet", "nombre", "apellido", "password"}, Proyectoprogra1.alumnos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Alumno a : Proyectoprogra1.alumnos) {
            jTable1.setValueAt(a.getCarnet(), row, 0);
            jTable1.setValueAt(a.getNombre(), row, 1);
            jTable1.setValueAt(a.getApellido(), row, 2);
            jTable1.setValueAt(a.getPassword(), row, 3);
            row++;
        }
    }

    public void actualizarDatos() {
        DefaultTableModel data = new DefaultTableModel(new String[]{"Carnet", "nombre", "apellido", "password"}, Proyectoprogra1.alumnos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Alumno a : Proyectoprogra1.alumnos) {
            jTable1.setValueAt(a.getCarnet(), row, 0);
            jTable1.setValueAt(a.getNombre(), row, 1);
            jTable1.setValueAt(a.getApellido(), row, 2);
            jTable1.setValueAt(a.getPassword(), row, 3);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_modificar = new javax.swing.JButton();
        btn_salir1 = new javax.swing.JButton();
        btn_cargarXML = new javax.swing.JButton();
        btn_guardarXML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Consultar Alumnos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_modificar.setBackground(new java.awt.Color(102, 255, 102));
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_salir1.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir1.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir1.setText("Salir");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        btn_cargarXML.setBackground(new java.awt.Color(255, 255, 204));
        btn_cargarXML.setText("Carga masiva XML");
        btn_cargarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarXMLActionPerformed(evt);
            }
        });

        btn_guardarXML.setBackground(new java.awt.Color(255, 255, 204));
        btn_guardarXML.setText("Guardar XML");
        btn_guardarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardarXML)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cargarXML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modificar)
                        .addGap(95, 95, 95)
                        .addComponent(btn_salir1)))
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir1)
                    .addComponent(btn_modificar)
                    .addComponent(btn_cargarXML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardarXML)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        Editar_Alumno a = new Editar_Alumno(jTable1.getSelectedRow());
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        Admin a = new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_cargarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarXMLActionPerformed
        JFileChooser archivo = new JFileChooser("");
        int seleccionado = archivo.showDialog(this, "Cargar");
        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            leerArchivoXMLAlumnos(archivo.getSelectedFile());
            JOptionPane.showMessageDialog(this, "Archivo Cargado");
        }
    }//GEN-LAST:event_btn_cargarXMLActionPerformed

    private void btn_guardarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarXMLActionPerformed
        String contenido = "<alumnos>\n";

        for (Alumno a : Proyectoprogra1.alumnos) {
            contenido += "\t<alumno>\n";
            contenido += "\t\t<carne>";
            contenido += a.getCarnet();
            contenido += "</carne>\n";
            contenido += "\t\t<nombre>";
            contenido += a.getNombre();
            contenido += "</nombre>\n";
            contenido += "\t\t<apellido>";
            contenido += a.getApellido();
            contenido += "</apellido>\n";
            contenido += "\t\t<password>";
            contenido += a.getPassword();
            contenido += "</password>\n";
            contenido += "\t</alumno>\n";
        }
        contenido += "</alumnos>";

        JFileChooser archivo = new JFileChooser("");
        int seleccionado = archivo.showDialog(this, "Guardar");
        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            guardarXML(archivo.getSelectedFile().toPath().toString(), contenido);
            JOptionPane.showMessageDialog(this, "Contenido Guardado");

        }

    }//GEN-LAST:event_btn_guardarXMLActionPerformed
    public void leerArchivoXMLAlumnos(File archivo) {

        try {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            Document doc = db.parse(archivo);

            doc.getDocumentElement().normalize();
            NodeList nodos = doc.getElementsByTagName("alumno");

            for (int i = 0; i < nodos.getLength(); i++) {
                Node n = nodos.item(i);
                if (n.getNodeType() == Node.ELEMENT_NODE) {
                    Element a = (Element) n;
                    Alumno am = new Alumno();
                    am.setCarnet(a.getElementsByTagName("carne")
                            .item(0)
                            .getTextContent());
                    am.setNombre(a.getElementsByTagName("nombre")
                            .item(0)
                            .getTextContent());
                    am.setApellido(a.getElementsByTagName("apellido")
                            .item(0)
                            .getTextContent());
                    am.setPassword(a.getElementsByTagName("password")
                            .item(0)
                            .getTextContent());
                    Proyectoprogra1.alumnos.add(am);
                }

            }
            actualizarDatos();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void guardarXML(String rutaConNombre, String contenido) {
        try {

            FileWriter fw = new FileWriter(rutaConNombre);
            PrintWriter pw = new PrintWriter(fw);
            pw.write(contenido);
            pw.close();
            fw.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarXML;
    private javax.swing.JButton btn_guardarXML;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
