/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra1;

import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author javier
 */
public class Consultar_cursos extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_cursos
     */
    public Consultar_cursos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consultar Cursos creados");

        DefaultTableModel data = new DefaultTableModel(new String[]{"ID", "Nombre", "Sección", "Fecha inicio", "Fecha fin", "Hora inicio", "Hora fin", "Profesor"}, Proyectoprogra1.cursos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Curso c : Proyectoprogra1.cursos) {
            jTable1.setValueAt(c.getID(), row, 0);
            jTable1.setValueAt(c.getNombre(), row, 1);
            jTable1.setValueAt(c.getSeccion(), row, 2);
            jTable1.setValueAt(c.getFecha_inicio(), row, 3);
            jTable1.setValueAt(c.getFecha_fin(), row, 4);
            jTable1.setValueAt(c.getH_inicio(), row, 5);
            jTable1.setValueAt(c.getH_fin(), row, 6);
            jTable1.setValueAt(c.getProfesor(), row, 7);
            row++;
        }

    }

    public void actualizarDatos() {
        DefaultTableModel data = new DefaultTableModel(new String[]{"ID", "Nombre", "Sección", "Fecha inicio", "Fecha fin", "Hora inicio", "Hora fin", "Profesor"}, Proyectoprogra1.cursos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Curso c : Proyectoprogra1.cursos) {
            jTable1.setValueAt(c.getID(), row, 0);
            jTable1.setValueAt(c.getNombre(), row, 1);
            jTable1.setValueAt(c.getSeccion(), row, 2);
            jTable1.setValueAt(c.getFecha_inicio(), row, 3);
            jTable1.setValueAt(c.getFecha_fin(), row, 4);
            jTable1.setValueAt(c.getH_inicio(), row, 5);
            jTable1.setValueAt(c.getH_fin(), row, 6);
            jTable1.setValueAt(c.getProfesor(), row, 7);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_salir1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_cargarJS = new javax.swing.JButton();

        jLabel4.setBackground(new java.awt.Color(102, 204, 255));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_salir1.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir1.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir1.setText("Salir");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Consultar Cursos");

        btn_modificar.setBackground(new java.awt.Color(102, 255, 102));
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_cargarJS.setBackground(new java.awt.Color(255, 255, 204));
        btn_cargarJS.setText("Carga masiva js");
        btn_cargarJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarJSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_cargarJS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modificar)
                .addGap(126, 126, 126)
                .addComponent(btn_salir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargarJS)
                    .addComponent(btn_modificar)
                    .addComponent(btn_salir1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        Admin a = new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        Modificar_Curso m = new Modificar_Curso(jTable1.getSelectedRow());
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_cargarJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarJSActionPerformed
        JFileChooser archivo = new JFileChooser();
        int result = archivo.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            cargarJSON(archivo.getSelectedFile().getPath());
            JOptionPane.showMessageDialog(this, "Archivo Cargado");
        }
    }//GEN-LAST:event_btn_cargarJSActionPerformed
    public void cargarJSON(String rutaConNombre) {
        JSONParser parser = new JSONParser();

        try (FileReader reader = new FileReader(rutaConNombre)) {
            Object obj = parser.parse(reader);
            JSONArray cursosList = (JSONArray) obj;

            for (Object c : cursosList) {
                JSONObject cursoObj = (JSONObject) c;

                if (cursoObj != null) {
                    Object idObject = cursoObj.get("id");
                    int ID = (idObject != null) ? ((Long) idObject).intValue() : 1;
                    String Nombre = (String) cursoObj.get("nombre");
                    String Seccion = (String) cursoObj.get("seccion");
                    String Fecha_inicio = (String) cursoObj.get("fecha_inicio");
                    String Fecha_fin = (String) cursoObj.get("fecha_fin");
                    String H_inicio = (String) cursoObj.get("hora_inicio");
                    String H_fin = (String) cursoObj.get("hora_fin");
                    String profesor = (String) cursoObj.get("profesor");

                    Curso o = new Curso();
                    o.setID(ID);
                    o.setNombre(Nombre);
                    o.setSeccion(Seccion);
                    o.setFecha_inicio(Fecha_inicio);
                    o.setFecha_fin(Fecha_fin);
                    o.setH_inicio(H_inicio);
                    o.setH_fin(H_fin);
                    o.setProfesor(profesor);

                    Proyectoprogra1.cursos.add(o);
                }
            }
            actualizarDatos();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarJS;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
