/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class Consultar_profesores extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Cursos
     */
    public Consultar_profesores() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consultar Profesores creados");
        
        DefaultTableModel data = new DefaultTableModel(new String[]{"usuario", "nombre", "apellido", "password"}, Proyectoprogra1.profesores.size());
        jTable1.setModel(data);

        int row = 0;
        
        for(Profesor p : Proyectoprogra1.profesores){
            jTable1.setValueAt(p.usuario, row, 0);
            jTable1.setValueAt(p.nombre, row, 1);
            jTable1.setValueAt(p.apellido, row, 2);
            jTable1.setValueAt(p.password, row, 3);
            row ++;
        }
    }
    public void actualizarDatos(){
        DefaultTableModel data = new DefaultTableModel(new String[]{"usuario", "nombre", "apellido", "password"}, Proyectoprogra1.profesores.size());
        jTable1.setModel(data);
        
        int row = 0;
        
        for(Profesor p : Proyectoprogra1.profesores){
            jTable1.setValueAt(p.usuario, row, 0);
            jTable1.setValueAt(p.nombre, row, 1);
            jTable1.setValueAt(p.apellido, row, 2);
            jTable1.setValueAt(p.password, row, 3);
            row ++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_modificar = new javax.swing.JButton();
        btn_salir1 = new javax.swing.JButton();
        btn_cargarcsv = new javax.swing.JButton();
        btn_guardarCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Consultar Profesores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_modificar.setBackground(new java.awt.Color(102, 255, 102));
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_salir1.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir1.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir1.setText("Salir");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        btn_cargarcsv.setBackground(new java.awt.Color(255, 255, 204));
        btn_cargarcsv.setText("Carga masiva CSV");
        btn_cargarcsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarcsvActionPerformed(evt);
            }
        });

        btn_guardarCSV.setBackground(new java.awt.Color(255, 255, 204));
        btn_guardarCSV.setText("Guardar CSV");
        btn_guardarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_cargarcsv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_modificar)
                                .addGap(280, 280, 280)
                                .addComponent(btn_salir1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_guardarCSV)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir1)
                    .addComponent(btn_modificar)
                    .addComponent(btn_cargarcsv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardarCSV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        Editar_Profesor p = new Editar_Profesor(jTable1.getSelectedRow());
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        Admin a = new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_cargarcsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarcsvActionPerformed
        JFileChooser archivo = new JFileChooser("");
        int seleccionado = archivo.showDialog(this,"Cargar");
        if(seleccionado==JFileChooser.APPROVE_OPTION){
            leerArchivoTextoProfesor(archivo.getSelectedFile().toPath().toString());
            JOptionPane.showMessageDialog(this, "Archivo Cargado");
        }
    }//GEN-LAST:event_btn_cargarcsvActionPerformed

    private void btn_guardarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCSVActionPerformed
        StringBuilder contenido = new StringBuilder();
        for (Profesor p : Proyectoprogra1.profesores) {
            contenido.append(p.usuario).append(",");
            contenido.append(p.nombre).append(",");
            contenido.append(p.apellido).append(",");
            contenido.append(p.password).append("\n");
        }
        
        JFileChooser archivo = new JFileChooser("");
        int seleccionado = archivo.showDialog(this, "Guardar");
        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            guardarCSV(archivo.getSelectedFile().toPath().toString(), contenido.toString());
            JOptionPane.showMessageDialog(this, "Contenido Guardado");
        }
    }//GEN-LAST:event_btn_guardarCSVActionPerformed
    public void leerArchivoTextoProfesor(String rutaConNombre){
        
        try{
            File f = new File(rutaConNombre);
            FileReader fr = new FileReader(f);
            
            BufferedReader br = new BufferedReader(fr);
            
            String linea;
            while((linea=br.readLine())!=null){
                String[] contenidoLinea = linea.split(",");
                Profesor p = new Profesor();
                p.usuario = contenidoLinea[0];
                p.nombre = contenidoLinea[1];
                p.apellido = contenidoLinea[2];
                p.password = contenidoLinea[3];
                Proyectoprogra1.profesores.add(p);
            }
        actualizarDatos();
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    public static void guardarCSV(String rutaConNombre, String contenido){
        try (
            FileWriter fw = new FileWriter(rutaConNombre);
            PrintWriter pw = new PrintWriter(fw)) {
            pw.write(contenido);
        } catch (Exception e) {
            e.printStackTrace();
        }
   }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarcsv;
    private javax.swing.JButton btn_guardarCSV;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
