/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class listado_e_asignados extends javax.swing.JFrame {

    /**
     * Creates new form listado_e_asignados
     */
    public listado_e_asignados() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consultar estudiantes asignados");

        DefaultTableModel data = new DefaultTableModel(new String[]{"Carnet", "Nombre", "Apellido", "Nota"}, 0);
        jTable2.setModel(data);

        for (Curso c : Proyectoprogra1.cursos) {
            jComboBox1.addItem(c.toString());
        }

    }

    /**
     * + c.Seccion This method is called from within the constructor to
     * initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_cargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Curso");

        btn_buscar.setBackground(new java.awt.Color(0, 204, 0));
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consultar Estudiantes Asignados");

        btn_cargar.setText("Asignacion masiva de estudiantes");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btn_salir)
                        .addGap(39, 39, 39)
                        .addComponent(btn_buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btn_cargar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cargar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        Curso cursoSeleccionado = null;
        String nombreCurso = jComboBox1.getSelectedItem().toString();

        for (Curso c : Proyectoprogra1.cursos) {
            if (c.toString().equals(nombreCurso)) {
                cursoSeleccionado = c;
                break;
            }
        }

        if (cursoSeleccionado != null) {
            DefaultTableModel data = new DefaultTableModel(new String[]{"Carnet", "Nombre", "Apellido", "Nota"}, cursoSeleccionado.getAlumnos().size());
            jTable2.setModel(data);

            int row = 0;

            for (Alumno e : cursoSeleccionado.getAlumnos()) {
                jTable2.setValueAt(e.getCarnet(), row, 0);
                jTable2.setValueAt(e.getNombre(), row, 1);
                jTable2.setValueAt(e.getApellido(), row, 2);
                jTable2.setValueAt(e.getNota(), row, 3);
                row++;
            }
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        Admin a = new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        JFileChooser archivo = new JFileChooser();
        int result = archivo.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            cargarbin(archivo.getSelectedFile().getPath());
            JOptionPane.showMessageDialog(this, "Archivo Cargado");
        }
    }//GEN-LAST:event_btn_cargarActionPerformed
    private void cargarbin(String rutaConNombre) {
        try {
            BufferedReader br = new BufferedReader(new FileReader(rutaConNombre));
            String linea = null;

            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split("#");
                if (partes.length == 2) {
                    String cursoID = partes[0];
                    String carnet = partes[1];

                    Alumno alumnoSeleccionado = null;
                    Curso cursoSeleccionado = null;
                    
                    for (Alumno a : Proyectoprogra1.alumnos) {
                        if (a.getCarnet().equals(carnet)) {
                            alumnoSeleccionado = a;
                            break;
                        }
                    }
                    
                    for (Curso c : Proyectoprogra1.cursos) {
                        if (Integer.toString(c.getID()).equals(cursoID)) {
                            cursoSeleccionado = c;
                            break;
                        }
                    }
                    if (cursoSeleccionado != null && alumnoSeleccionado != null) {
                        Alumno a = new Alumno();
                        a.setNombre(alumnoSeleccionado.getNombre());
                        a.setApellido(alumnoSeleccionado.getApellido());
                        a.setCarnet(alumnoSeleccionado.getCarnet());
                        a.setPassword(alumnoSeleccionado.getPassword());
                        a.setNota(alumnoSeleccionado.getNota());
                        cursoSeleccionado.getAlumnos().add(a);
                    }
                }
            }
            br.close();
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
